

services:
  postgres:
    image: postgres:15
    container_name: meteo_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  backend:
    build: ./backend
    container_name: meteo_backend
    depends_on:
      - postgres
    volumes:
      - ./backend/app:/app/app
      - ./backend/models:/app/app/models
    ports:
      - "8000:8000"
    env_file:
      - .env


volumes:
  pgdata: