services:
  - type: web
    name: meteo-backend
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /ping
    envVars:
      - key: PORT
        value: 8000
      - key: DB_NAME
        fromDatabase:
          name: meteo-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: meteo-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: meteo-postgres
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: meteo-postgres
          property: connectionString
      - key: KBELY
        value: "LKKB, 50.12, 14.54, 286"
      - key: HISTORY_DATA_API_URL
        value: "https://aviationweather.gov/api/data/metar"
      - key: FORECAST_DATA_API_URL
        value: "https://api.met.no/weatherapi/locationforecast/2.0/complete"
      - key: FORECAST_HEADER
        value: "User-Agent: MeteoApp/1.0 mansfmat@cvut.cz"
      - key: DB_HOST
        fromDatabase:
          name: meteo-postgres
          property: host

databases:
  - name: meteo-postgres
    databaseName: meteo_db
    user: meteo_user
    region: frankfurt
    plan: free
    postgresMajorVersion: "15"
